version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ctf_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ctf_platform
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ctf_network

  backend:
    build: .
    container_name: ctf_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/ctf_platform?authSource=admin
      DATABASE_NAME: ctf_platform
      SECRET_KEY: your-production-secret-key-change-this
      ADMIN_EMAIL: admin@ctf.com
      ADMIN_PASSWORD: admin123
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:8000
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    networks:
      - ctf_network

volumes:
  mongodb_data:

networks:
  ctf_network:
    driver: bridge
